export const MAIN_PATH = () => '/';
export const AUTH_PATH = () => '/auth';
export const OAUTH_PATH = () => '/auth/oauth-response/:token/:expirationTime/:tempUsername?';
// export const REVIEW_PATH = () => '/review';
export const FACULTY_PATH = () => 'review';
export const FACULTY_PATH_WITH_CODE = (facultyName: string) => `review/${facultyName}`;
export const STUDY_PATH = (faculty: string, studyCode: string) => `/review/${faculty}/${studyCode}`;
export const COURSE_PATH = (faculty: string, studyCode: string, courseCode: string) => `/review/${faculty}/${studyCode}/${courseCode}`;
export const USER_PATH = (userEmail: string) => `/user/${userEmail}`;
// export const SEARCH_PATH = (searchWord: string) => `/search/${searchWord}`;

export const subjectCodeMap: { [key: string]: string } = {
    "Academic English Studies": "ACADENG",
    "Academic Integrity": "ACADINT",
    "Accounting": "ACCTG",
    "Aerospace Engineering": "AEROSPCE",
    "Anthropology": "ANTHRO",
    "Architectural Design": "ARCHDES",
    "Architectural History, Theory and Criticism": "ARCHHTC",
    "Architectural Media and Fabrication": "ARCHDRC",
    "Architectural Professional Studies": "ARCHPRM",
    "Architectural Technology and Sustainability": "ARCHTECH",
    "Architecture – General": "ARCHGEN",
    "Artificial Intelligence and Society": "TDAIS",
    "Art History": "ARTHIST",
    "Arts General": "ARTSGEN",
    "Arts Scholars": "ARTSCHOL",
    "Asian Studies": "ASIAN",
    "Astrosciences": "ASTRO",
    "Audiology": "AUDIOL",
    "Bioengineering": "BIOENG",
    "Bioinformatics": "BIOINF",
    "Biological Sciences": "BIOSCI",
    "Biomedical Engineering": "BIOMENG",
    "Biomedical Science": "BIOMED",
    "Biosecurity and Conservation": "BIOSEC",
    "Biotechnology": "BIOTECH",
    "Built Environment": "BLTENV",
    "Business": "BUSINESS",
    "Business Accounting": "BUSACT",
    "Business Analytics": "BUSAN",
    "Business Development": "BUSDEV",
    "Business Finance": "BUSFIN",
    "Business Human Resource Management": "BUSHRM",
    "Business Information Analytics": "BUSINFO",
    "Business International": "BUSINT",
    "Business Management": "BUSMAN",
    "Business Marketing": "BUSMKT",
    "Business MBA": "BUSMBA",
    "Career": "CAREER",
    "Chemical and Materials Engineering": "CHEMMAT",
    "Chemistry": "CHEM",
    "Chinese": "CHINESE",
    "Civil Engineering": "CIVIL",
    "Classical Studies and Ancient History": "ANCIENT",
    "Clinical Education": "CLINED",
    "Clinical Imaging": "CLINIMAG",
    "Commercial Law": "COMLAW",
    "Communication": "COMMS",
    "Comparative Literature": "COMPLIT",
    "Computer Science": "COMPSCI",
    "Computer Systems Engineering": "COMPSYS",
    "Cook Islands Māori": "COOKIS",
    "Creative Writing": "CREWRIT",
    "Criminology": "CRIM",
    "Dance Studies": "DANCE",
    "Data Science": "DATASCI",
    "Democracy in the 21st Century": "TDDEM",
    "Design": "DESIGN",
    "Development Studies": "DEVELOP",
    "Digital Health": "DIGIHLTH",
    "Disability Studies": "DISABLTY",
    "Disaster Management": "DISMGT",
    "Dietetics": "DIETETIC",
    "Drama": "DRAMA",
    "Earth Sciences": "EARTHSCI",
    "Ecology": "ECOLOG",
    "Economics": "ECON",
    "Education": "EDUC",
    "Education Curriculum Māori": "EDCURRM",
    "Education Curriculum Pasifika": "EDCURRPK",
    "Education Curriculum Secondary Diploma": "EDCURSEC",
    "Education Curriculum Studies": "EDCURRIC",
    "Education Māori": "EDUCM",
    "Education Practice": "EDPRAC",
    "Education Practice Māori": "EDPRACM",
    "Education Practice Pasifika": "EDPRACPK",
    "Education Professional": "EDPROF",
    "Education Professional Studies": "EDPROFST",
    "Education Professional Studies Māori": "EDPROFM",
    "Education Professional Studies Pasifika": "EDPROFPK",
    "Education Studies": "EDUCN",
    "Education and Social Work": "EDUCSW",
    "Educational Psychology": "EDPSYCH",
    "Electrical and Electronic Engineering": "ELECTENG",
    "Energy": "ENERGY",
    "Energy Technology": "GEOTHERM",
    "Engineering General": "ENGGEN",
    "Engineering Science": "ENGSCI",
    "English": "ENGLISH",
    "English for Academic Purposes": "ENGLACP",
    "English Writing": "ENGWRIT",
    "Environment": "ENV",
    "Environmental Change": "ENVCHG",
    "Environmental Engineering": "ENVENG",
    "Environmental Management": "ENVMGT",
    "Environmental Physics": "ENVPHYS",
    "Environmental Science": "ENVSCI",
    "European Studies": "EUROPEAN",
    "Exercise Sciences": "EXERSCI",
    "Finance": "FINANCE",
    "Fine Arts": "FINEARTS",
    "Food Science": "FOODSCI",
    "Forensic Science": "FORENSIC",
    "Foundation Studies": "FOUNDST",
    "French": "FRENCH",
    "Gender Studies": "GENDER",
    "Geographic Information Science": "GISCI",
    "Geography": "GEOG",
    "Geophysics": "GEOPHYS",
    "German": "GERMAN",
    "Global Management and Innovation": "GLMI",
    "Global Studies": "GLOBAL",
    "Health Education": "HEALTHED",
    "Health Management": "HLTHMGT",
    "Health Psychology": "HLTHPSYC",
    "Health Sciences": "HLTHSCI",
    "Heritage Conservation": "HERCONS",
    "Higher Education": "HIGHED",
    "History": "HISTORY",
    "Human Services": "HUMSERV",
    "Humanities": "HUMS",
    "Indigenous Studies": "INDIGEN",
    "Information Governance": "INFOGOV",
    "Information Management": "INFOMGMT",
    "Information Systems": "INFOSYS",
    "Innovation and Entrepreneurship": "INNOVENT",
    "International Business": "INTBUS",
    "Internship": "INTERNSP",
    "Italian": "ITALIAN",
    "Japanese": "JAPANESE",
    "Korean": "KOREAN",
    "Language Teaching and Learning": "LANGTCHG",
    "Latin": "LATIN",
    "Latin American Studies": "LATINAM",
    "Law": "LAW",
    "Law Commercial": "LAWCOMM",
    "Law Environmental": "LAWENVIR",
    "Law General": "LAWGENRL",
    "Law Honours": "LAWHONS",
    "Law Public": "LAWPUBL",
    "Leadership and Governance": "LDGOV",
    "Linguistics": "LINGUIST",
    "Logic and Computation": "LOGICOMP",
    "Management": "MGMT",
    "Marine Science": "MARINE",
    "Marketing": "MKTG",
    "Mathematics": "MATHS",
    "Māori Development": "MAORIDEV",
    "Māori Health": "MAORIHTH",
    "Māori Studies": "MĀORI",
    "Mātauranga": "MĀTAU",
    "MBChB": "MBCHB",
    "Mechanical Engineering": "MECHENG",
    "Mechatronics Engineering": "MECHTRON",
    "Media and Screen Studies": "MEDIA",
    "Medical Imaging": "MEDIMAGE",
    "Medical Science": "MEDSCI",
    "Medicine": "MEDICINE",
    "Migration Futures": "TDMIGR",
    "Music": "MUS",
    "Museums and Cultural Heritage": "MUSEUMS",
    "Nursing": "NURSING",
    "Nursing Practice": "NURSPRAC",
    "Obstetrics and Gynaecology": "OBSTGYN",
    "Operations and Supply Chain Management": "OPSMGT",
    "Ophthalmology": "OPHTHAL",
    "Optometry and Vision Science": "OPTOM",
    "Our Environmental Futures: Te Taiao Tāngata": "TDENVF",
    "Pacific Studies": "PACIFIC",
    "Paediatrics": "PAEDS",
    "Pharmacy": "PHARMACY",
    "Pharmacology": "PHARMCOL",
    "Philosophy": "PHIL",
    "Physical Education": "PHYSED",
    "Physics": "PHYSICS",
    "Physiology": "PHYSIOL",
    "Politics and International Relations": "POLITICS",
    "Polymer Engineering": "POLYMER",
    "Population Health": "POPLHLTH",
    "Population Health Practice": "POPLPRAC",
    "Professional Counselling": "PROFCOUN",
    "Professional Supervision": "PROFSUPV",
    "Property": "PROPERTY",
    "Property Practice": "PROPPRAC",
    "Psychiatry": "PSYCHIAT",
    "Psychology": "PSYCH",
    "Public Policy": "POLICY",
    "Pūtaiao": "PŪTAIAO",
    "Regional Development": "REGDEV",
    "Russian": "RUSSIAN",
    "Samoan": "SAMOAN",
    "Science Enterprise": "SCIENT",
    "Science Scholars": "SCIGEN",
    "Screen Production": "SCREEN",
    "Social Justice": "SOCJUS",
    "Social Work": "SOCWORK",
    "Social Work Child and Family Practice": "SOCCHFAM",
    "Social Work Health Practice": "SOCHLTH",
    "Social Work Youth Practice": "SOCYOUTH",
    "Social and Community Leadership": "SOCCLEAD",
    "Sociology": "SOCIOL",
    "Software Engineering": "SOFTENG",
    "Spanish": "SPANISH",
    "Speech Science": "SPCHSCI",
    "Sport Studies": "SPORT",
    "Sport, Health and Physical Education": "SPORTHPE",
    "Statistics": "STATS",
    "Structural Engineering": "STRCTENG",
    "Sustainability": "SUSTAIN",
    "Tagata Moana, Tangata Whenua: Hawaiki Futures": "TDMOANA",
    "Tertiary Foundation Certificate Arts General": "TFCARTS",
    "Tertiary Foundation Certificate Biological Science": "TFCBIO",
    "Tertiary Foundation Certificate Business": "TFCBUS",
    "Tertiary Foundation Certificate Chemistry": "TFCCHEM",
    "Tertiary Foundation Certificate Creative Arts": "TFCCAI",
    "Tertiary Foundation Certificate Education": "TFCEDUC",
    "Tertiary Foundation Certificate English": "TFCENG",
    "Tertiary Foundation Certificate Environmental Studies": "TFCENV",
    "Tertiary Foundation Certificate History": "TFCHIST",
    "Tertiary Foundation Certificate Mathematics": "TFCMATHS",
    "Tertiary Foundation Certificate Māori": "TFCMAORI",
    "Tertiary Foundation Certificate Pacific Studies": "TFCPAC",
    "Tertiary Foundation Certificate Physics": "TFCPHYS",
    "Tertiary Foundation Certificate Sociology": "TFCSOCIO",
    "Tertiary Foundation Certificate Statistics": "TFCSTATS",
    "The Future of Food": "TDFOOD",
    "Theology": "THEOLOGY",
    "Theological and Religious Studies": "THEOREL",
    "Tongan": "TONGAN",
    "Translation Studies": "TRANSLAT",
    "University of Auckland Foundation Studies": "CTFOUND",
    "Urban Design": "URBDES",
    "Urban Planning": "URBPLAN",
    "Wine Science": "WINESCI",
    "Youth Work": "YOUTHWRK"
  };

export const codeToSubjectMap: { [key: string]: string } = {};
  for (const [subject, code] of Object.entries(subjectCodeMap)) {
    codeToSubjectMap[code] = subject;
}